import React from 'react'

export const Home = () => (
    <div>
        <h2>Hello World</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse convallis urna in dictum pellentesque. Proin rutrum justo eget ex commodo imperdiet. Proin velit nunc, condimentum nec pretium vitae, mollis at enim. Nam mauris massa, commodo ut ultrices id, bibendum non sapien. Integer vulputate, tortor eget sodales tristique, ex nunc consequat lectus, vel vestibulum arcu tortor vitae ante. Maecenas venenatis aliquet risus, eu ultricies mauris dictum id. Fusce posuere velit magna, sit amet dignissim diam finibus eget. Quisque pulvinar, libero suscipit venenatis interdum, nibh erat rutrum odio, et sollicitudin turpis nulla sed odio. Ut non consequat massa. Nullam a sodales est, quis blandit justo. Phasellus dolor ex, fringilla faucibus maximus facilisis, tincidunt vitae purus. Integer placerat blandit ipsum, a condimentum turpis commodo at. Phasellus non diam ac tortor vehicula euismod.</p>
        <p>Mauris eu ipsum quam. Pellentesque arcu neque, mollis eu quam auctor, consequat hendrerit purus. Curabitur molestie, nulla non dignissim eleifend, enim ex viverra massa, a rhoncus dui diam id ligula. Vivamus et eleifend quam, eu congue nulla. Proin vel ornare nisl. Nulla rhoncus nisl id magna vestibulum aliquet. Nunc eleifend, ligula accumsan consequat porttitor, libero nibh commodo sapien, eu convallis sapien turpis nec nulla. Duis luctus, libero vitae condimentum egestas, lectus sapien tempus neque, interdum bibendum metus justo quis tellus. Mauris sagittis urna urna. Curabitur ullamcorper felis ac tellus varius pharetra. Morbi neque dolor, aliquet imperdiet dapibus tincidunt, viverra at diam. Nam mattis quam in risus suscipit semper.</p>
        <p>Phasellus mattis, arcu quis rhoncus blandit, ipsum nisi semper neque, at dictum neque lacus eget sem. Aliquam commodo blandit dui at commodo. Fusce a aliquam diam. Pellentesque consequat a quam in rutrum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam blandit tincidunt dolor, et consequat felis fermentum et. Maecenas vehicula malesuada quam, suscipit fringilla dolor faucibus vel. Duis eget pulvinar ipsum, ac laoreet sem. Ut et porttitor diam. Fusce sed consectetur ligula, aliquam sodales nibh. Donec vehicula aliquet dictum. Cras nulla nulla, volutpat sed lacus nec, placerat mattis libero. Suspendisse non nulla rhoncus, molestie arcu a, vestibulum sem. Nulla eget malesuada leo. Aenean ut sapien leo. Fusce feugiat lacus sed porta tincidunt.</p>
    </div>
)